### ISSUE TITLE
CF template showcase.yml showing error

### ISSUE THREAD

**Issue by subinmath** [widdix/aws-ec2-ssh#103]
Operating System: Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
AWS CLI Version: aws-cli/1.14.13 Python/3.5.2 Linux/4.4.0-1041-aws botocore/1.8.17
Error
----------------------------------------------------------------
when i run the CF template i get the following error

  | 12:52:20 UTC+0550 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | sshkeys | The following resource(s) failed to create: [Instance]. . Rollback requested by user.
-- | -- | -- | -- | -- | --
  | Physical ID:arn:aws:cloudformation:us-east-1:753611216131:stack/sshkeys/fd373730-e553-11e7-a1c6-500c217b48d2
  | Client Request Token:Console-CreateStack-dd8ba1cd-705a-4821-951a-98485086ffc1
  | 12:52:19 UTC+0550 | CREATE_FAILED | AWS::EC2::Instance | Instance | Failed to receive 1 resource signal(s) within the specified duration
  | Physical ID:i-001d50ba26b4c1c82
  | Client Request Token:Console-CreateStack-dd8ba1cd-705a-4821-951a-98485086ffc1
  | 12:36:46 UTC+0550 | CREATE_IN_PROGRESS | AWS::EC2::Instance | Instance | Resource creation Initiated
  | Physical ID:i-001d50ba26b4c1c82
  | Client Request Token:Console-CreateStack-dd8ba1cd-705a-4821-951a-98485086ffc1
  | 12:36:44 UTC+0550 | CREATE_IN_PROGRESS | AWS::EC2::Instance | Instance

**Comment by michaelwittig** [comment]
This is caused by #99

**Comment by KusabiSensei** [comment]
I would be interested in seeing the instance level logs, since I am not able to recreate this exact scenario on the 16.04.3 LTS AMIs using the showcase prior to making the changes in #105. Even after applying #105, I'm getting the expected behavior (and the Maven test suite is also passing now).

@subinmath If you can recreate the scenario, send along the event details in CloudFormation. I'd also recommend adding a key pair and assigning that to the instance, and setting CF to not roll back. It would better help us determine the exact cause of this failure scenario.

**Comment by michaelwittig** [comment]
related to #104
