### ISSUE TITLE
Consider documenting 'limits'?

### ISSUE THREAD

**Issue by uberbrady** [widdix/aws-ec2-ssh#5]
I absolutely _love_ this solution, it's what I've been looking for for literally _years_.

I am wondering what its limits are. I'm going to be setting it up for along the lines of 5 users or less - not going too nuts. And not on too many servers, either. I think it'll fit there just fine.

But I can imagine if you have, like 100 users or something - it might start to suck there (all those users getting added - could start to fill up your root disk?). Or if you have maybe 1000 servers - having each of them list every single user available in IAM every 10 minutes could start to cause a strain or throttling of your ability to make IAM queries.

Though, some of the nice things - if your connection to IAM were not quite working, 'old' users could still log in. Though they'd still have to be able to fetch the appropriate SSH key, so even if "List IAM Users" call stopped working, the "Get User's SSH Key" one would have to stay working. But also - even if your VPC NAT gateway goes down, you ought to still be able to log in (since it doesn't require external connectivity).

So I was wondering if that's something you'd consider documenting (if you agree with me on my ideas for where the limits might lie). Or if you'd like me to take a swing at that, I'd be happy to help and put together a PR. I might put it as an 'Advantages/Disadvantages' type of thing if it were up to me.

Anyways, regardless of any of that, thank you 1000 times for this. It's the first time I've found a solution to this problem that feels like it actually fits.

**Comment by michaelwittig** [comment]
Hi @uberbrady

I agree with you that documenting the limitations is a good idea. My thoughts:

**regarding API limits**

* the import_users.sh script runs every 10 minutes and issues one API request for every 500 users multiplied by the number of servers. But I'm not aware of n official/documented API rate limit for the IAM service.
* the authorized_keys_command.sh script runs whenever a user logs in via ssh. The number of API requests is two multiplied by the number of logins

because of the lack of official documentation on APi rate limits, we can either test the limits or we can't document the limits correctly.

**regarding old users**

* if you delete an IAM user the IAM key is also deleted. so even if the list of users is not up-to-date the list-ssh-public-keys   / get-ssh-public-key call will not return a key if the user is deleted.
* all the aws cli commands require internet access either via IGW or NAT (except s3 + vpc s3 endpoint)

so I guess the limitation is that it can take up to 10 minutes until a new user can log in. I don't understand the other scenarios properly at the moment. Can you elaborate on them?


**one additional limitation I can think of:**

* the solution checks only on login. so if you delete the IAM user / key, and the user is already logged in the session will not be closed


**So the List of limitations so far:**

*  it can take up to 10 minutes until a new user can log in
*  if you delete the IAM user / ssh public key and the user is already logged in, the session will not be closed

**Comment by uberbrady** [comment]
The other ones I can think of - if you had an `/etc/skel` that was, let's say, hefty for some reason - (10's of MB; pretty unusual). Then every time you add another user to IAM, this solution would stamp out another 10 megs for that user - even users who might never end up logging in. So - say 5000 IAM users, 10 megs of each - 50,000 MB's of storage used up - around 50GB. Lots of AWS boxes have 8GB EBS volumes, for example. Other limits might be if `/etc/skel` contained lots of teeny little files, suddenly stamping out 5000 users might run you out of inodes on your root disk. (Ref: IAM limits doco: http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html). If we can figure out #2 somehow, that partially solves this (and gets rid of the 10 minute delay, *and* means we don't have to run a cronjob, and reduces load on IAM...)

Some more limitations:

- If IAM is down, or your instances can't access it for some reason, you can't SSH in (and neither can anyone else).
- Usage on 1000's of servers with 1000's of IAM users might start to be slow, or buggy? (As IAM calls start getting throttled...)
- IAM pagination might limit you to only looking at the first 500 users. (Or 'n' users, for whatever the default pagination might be...)
- Unix `uid`'s and `gid`'s across multiple servers might not line up correctly (due to when a server was booted, and what users existed at that time). Could affect NFS mounts or Amazon EFS.
- Any kind of non-trivial user/group mapping to login permissions requires some programming to implement. And, if done, might require rebooting servers to 'pick up' the new changes

Those are all the ones I can think of. But where I think it will shine is environments like mine where:

1. I don't care about user ID's, and don't use NFS (and won't in the near future).
2. I'm dealing with less than 5 users, I just want to be able to add/remove one of them without rushing across all of my servers.
3. I can deal with the 10 minute delay on a new hire. Hell, just orienting them ought to eat up most of those 10 minutes.
4. You can either login to servers, or you can't. That's it. That's all I care about.

If you want me to take another stab at another PR with this stuff in it, let me know. I love this solution and anything I can do to help, I'd love to do.

Again, thanks a billion for making this. I'm about to roll it out in anger and will report back if anything goes funny.

**Comment by michaelwittig** [comment]
@uberbrady I admit that this was not my fastest response this year: I added the limitations to the README.
