### ISSUE TITLE
On Ubuntu service is called ssh 

### ISSUE THREAD

**Issue by mariuz** [widdix/aws-ec2-ssh#72]
On ubuntu instances service is called ssh 

`service ssh restart`

**Comment by madave** [comment]
Additionally, the cron-scheduled import_users.sh seems to adversely delete all imported by install.sh users ten minutes later (at its first cron-scheduled exec). The iam-synced-users seems to remain though.

**Comment by michaelwittig** [comment]
@madave is this releated to #69

**Comment by michaelwittig** [comment]
I think the problem is that this solution is not intended to work with Ubuntu. The demo uses Amazon Linux https://github.com/widdix/aws-ec2-ssh#demo-with-cloudformation and also our tests (https://github.com/widdix/aws-ec2-ssh/tree/master/test) use Amazon Linux only.

Is anyone interested in fixing all the Ubuntu issues? I'm not using Ubuntu at all. I'm an Amazon Linux user.

**Comment by mliner** [comment]
Hi @michaelwittig, 
it seems that this issue still persists in the rpm where after installation /etc/ssh/sshd_config does not include these lines:
`AuthorizedKeysCommand /usr/bin/authorized_keys_command.sh
AuthorizedKeysCommandUser nobody`

Would it be possible to check? I've also tried newer version (1.5 and 1.6) and still the same issue. Trying to apply it on ubuntu 14.04 LTS.

Thanks in advance!

**Comment by michaelwittig** [comment]
@mliner I created #115 for this

**Comment by michaelwittig** [comment]
@mliner you can test with the nw RPM: https://s3-eu-west-1.amazonaws.com/widdix-aws-ec2-ssh-releases-eu-west-1/aws-ec2-ssh-1.7.0-1.el7.centos.noarch.rpm

Btw: Do you use rpms on Ubuntu?
